INSERT INTO Room (HotelID, Price, Amenities, Capacity, ViewType, CanBeExtended, HasDamage, ProblemDescription)
VALUES
(1, 162.5, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, TRUE, 'Leaky faucet in bathroom'),
(1, 194.4, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, FALSE, NULL),
(1, 263.94, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(1, 319.9, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, FALSE, NULL),
(1, 345.28, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(2, 154.6, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(2, 213.61, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(2, 255.88, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', FALSE, TRUE, 'TV screen cracked'),
(2, 304.6, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, FALSE, NULL),
(2, 353.51, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(3, 166.29, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(3, 197.57, 'TV, Air Condition, Fridge', 'Single', 'Mountain', FALSE, FALSE, NULL),
(3, 244.09, 'TV, Air Condition, Fridge', 'Double', 'None', FALSE, FALSE, NULL),
(3, 306.32, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, FALSE, NULL),
(3, 358.72, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(4, 160.98, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(4, 192.58, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(4, 253.29, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, FALSE, NULL),
(4, 285.42, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, TRUE, 'TV screen cracked'),
(4, 356.81, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(5, 155.67, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, TRUE, 'Desk drawer stuck'),
(5, 205.35, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, FALSE, NULL),
(5, 256.57, 'TV, Air Condition, Fridge', 'Double', 'Mountain', FALSE, FALSE, NULL),
(5, 280.32, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, TRUE, 'Broken balcony door lock'),
(5, 369.37, 'TV, Air Condition, Fridge', 'Single', 'Sea', FALSE, FALSE, NULL),
(6, 139.02, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, FALSE, NULL),
(6, 199.4, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, TRUE, 'Lighting issues in bathroom'),
(6, 247.56, 'TV, Air Condition, Fridge', 'Double', 'Mountain', FALSE, TRUE, 'TV screen cracked'),
(6, 288.95, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, TRUE, 'Lighting issues in bathroom'),
(6, 341.8, 'TV, Air Condition, Fridge', 'Double', 'Mountain', FALSE, FALSE, NULL),
(7, 154.51, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(7, 196.36, 'TV, Air Condition, Fridge', 'Single', 'Sea', FALSE, FALSE, NULL),
(7, 250.49, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(7, 318.27, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', FALSE, FALSE, NULL),
(7, 353.18, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, TRUE, 'Stained carpet near bed'),
(8, 164.39, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(8, 182.65, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(8, 245.73, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, TRUE, 'Broken balcony door lock'),
(8, 301.88, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(8, 362.85, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, TRUE, 'Lighting issues in bathroom'),
(9, 131.93, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, FALSE, NULL),
(9, 208.76, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, FALSE, NULL),
(9, 252.58, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, FALSE, NULL),
(9, 309.86, 'TV, Air Condition, Fridge', 'Double', 'Mountain', FALSE, FALSE, NULL),
(9, 365.35, 'TV, Air Condition, Fridge', 'Single', 'Mountain', FALSE, FALSE, NULL),
(10, 164.33, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(10, 213.18, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, TRUE, 'Stained carpet near bed'),
(10, 261.65, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, FALSE, NULL),
(10, 298.24, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(10, 344.2, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, FALSE, NULL),
(11, 132.24, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, TRUE, 'Lighting issues in bathroom'),
(11, 182.88, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, TRUE, 'Broken balcony door lock'),
(11, 246.24, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, TRUE, 'Lighting issues in bathroom'),
(11, 285.52, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, FALSE, NULL),
(11, 344.25, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, TRUE, 'Fridge not cooling properly'),
(12, 142.19, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', FALSE, FALSE, NULL),
(12, 206.13, 'TV, Air Condition, Fridge', 'Single', 'Mountain', FALSE, FALSE, NULL),
(12, 242.33, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(12, 311.02, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, TRUE, 'Leaky faucet in bathroom'),
(12, 332.98, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, TRUE, 'AC not working'),
(13, 141.25, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, TRUE, 'Window won''t open'),
(13, 187.61, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, TRUE, 'Desk drawer stuck'),
(13, 248.68, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(13, 295.46, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(13, 345.57, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(14, 142.59, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, FALSE, NULL),
(14, 192.82, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, FALSE, NULL),
(14, 241.55, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, FALSE, NULL),
(14, 298.05, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(14, 359.26, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, TRUE, 'Fridge not cooling properly'),
(15, 162.25, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(15, 192.83, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(15, 249.66, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, FALSE, NULL),
(15, 298.42, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, FALSE, NULL),
(15, 350.81, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, FALSE, NULL),
(16, 148.63, 'TV, Air Condition, Fridge', 'Single', 'Sea', FALSE, FALSE, NULL),
(16, 216.65, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, TRUE, 'AC not working'),
(16, 266.08, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, TRUE, 'Stained carpet near bed'),
(16, 290.21, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, TRUE, 'AC not working'),
(16, 345.36, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(17, 145.49, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, TRUE, 'Desk drawer stuck'),
(17, 184.06, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(17, 266.16, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, TRUE, 'Desk drawer stuck'),
(17, 295.3, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(17, 332.95, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, FALSE, NULL),
(18, 168.81, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(18, 198.31, 'TV, Air Condition, Fridge', 'Single', 'None', TRUE, FALSE, NULL),
(18, 232.43, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(18, 280.94, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(18, 330.18, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(19, 134.29, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, TRUE, 'Desk drawer stuck'),
(19, 202.38, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, TRUE, 'Window won''t open'),
(19, 255.02, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(19, 300.35, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, FALSE, NULL),
(19, 340.44, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, FALSE, NULL),
(20, 133.73, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(20, 206.51, 'TV, Air Condition, Fridge', 'Double', 'None', FALSE, FALSE, NULL),
(20, 269.68, 'TV, Air Condition, Fridge', 'Single', 'Mountain', FALSE, TRUE, 'Lighting issues in bathroom'),
(20, 287.21, 'TV, Air Condition, Fridge', 'Double', 'None', FALSE, FALSE, NULL),
(20, 366.56, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', FALSE, FALSE, NULL),
(21, 133.94, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, TRUE, 'Leaky faucet in bathroom'),
(21, 180.88, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(21, 243.35, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, FALSE, NULL),
(21, 285.45, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, FALSE, NULL),
(21, 350.68, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', TRUE, TRUE, 'Desk drawer stuck'),
(22, 143.14, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, TRUE, 'Lighting issues in bathroom'),
(22, 180.77, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, TRUE, 'Desk drawer stuck'),
(22, 248.75, 'TV, Air Condition, Fridge', 'Triple', 'Sea', FALSE, FALSE, NULL),
(22, 284.09, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, TRUE, 'Lighting issues in bathroom'),
(22, 353.34, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, TRUE, 'Lighting issues in bathroom'),
(23, 167.18, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, FALSE, NULL),
(23, 196.39, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(23, 236.44, 'TV, Air Condition, Fridge', 'Triple', 'Sea', FALSE, FALSE, NULL),
(23, 318.39, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, FALSE, NULL),
(23, 337.13, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, TRUE, 'Fridge not cooling properly'),
(24, 142.56, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, FALSE, NULL),
(24, 195.57, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(24, 259.71, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, FALSE, NULL),
(24, 294.89, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(24, 336.33, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(25, 161.89, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(25, 214.25, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, FALSE, NULL),
(25, 261.9, 'TV, Air Condition, Fridge', 'Single', 'Mountain', FALSE, FALSE, NULL),
(25, 295.2, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(25, 334.58, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, TRUE, 'Fridge not cooling properly'),
(26, 162.89, 'TV, Air Condition, Fridge', 'Double', 'None', FALSE, FALSE, NULL),
(26, 202.92, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(26, 242.49, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(26, 319.72, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', FALSE, FALSE, NULL),
(26, 355.72, 'TV, Air Condition, Fridge', 'Single', 'Sea', FALSE, FALSE, NULL),
(27, 169.6, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(27, 190.53, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, TRUE, 'Lighting issues in bathroom'),
(27, 239.32, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(27, 306.03, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, FALSE, NULL),
(27, 356.99, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(28, 161.65, 'TV, Air Condition, Fridge', 'Double', 'Mountain', FALSE, FALSE, NULL),
(28, 213.51, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, FALSE, NULL),
(28, 251.89, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, FALSE, NULL),
(28, 302.25, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, TRUE, 'Stained carpet near bed'),
(28, 347.49, 'TV, Air Condition, Fridge', 'Double', 'None', TRUE, TRUE, 'Broken balcony door lock'),
(29, 145.68, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(29, 204.16, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, FALSE, NULL),
(29, 239.85, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(29, 315.6, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, FALSE, NULL),
(29, 350.14, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, TRUE, 'Window won''t open'),
(30, 147.74, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, TRUE, 'Desk drawer stuck'),
(30, 190.79, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(30, 262.33, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(30, 295.38, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(30, 361.93, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, FALSE, NULL),
(31, 145.48, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, TRUE, 'Leaky faucet in bathroom'),
(31, 189.03, 'TV, Air Condition, Fridge', 'Quad', 'None', FALSE, FALSE, NULL),
(31, 257.68, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, FALSE, NULL),
(31, 293.94, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(31, 330.8, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(32, 139.37, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(32, 199.7, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(32, 252.81, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(32, 305.84, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(32, 366.73, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, FALSE, NULL),
(33, 157.1, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, TRUE, 'Window won''t open'),
(33, 200.96, 'TV, Air Condition, Fridge', 'Double', 'Mountain', FALSE, FALSE, NULL),
(33, 251.27, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', FALSE, FALSE, NULL),
(33, 286.57, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, TRUE, 'Desk drawer stuck'),
(33, 333.4, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, FALSE, NULL),
(34, 144.38, 'TV, Air Condition, Fridge', 'Single', 'Mountain', FALSE, FALSE, NULL),
(34, 205.02, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', TRUE, FALSE, NULL),
(34, 268.11, 'TV, Air Condition, Fridge', 'Single', 'None', FALSE, FALSE, NULL),
(34, 312.25, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(34, 334.89, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(35, 143.85, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', TRUE, FALSE, NULL),
(35, 186.63, 'TV, Air Condition, Fridge', 'Triple', 'None', TRUE, FALSE, NULL),
(35, 231.71, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(35, 283.75, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, FALSE, NULL),
(35, 340.04, 'TV, Air Condition, Fridge', 'Single', 'Sea', TRUE, TRUE, 'Desk drawer stuck'),
(36, 149.37, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(36, 212.32, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(36, 231.32, 'TV, Air Condition, Fridge', 'Triple', 'None', FALSE, FALSE, NULL),
(36, 288.18, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, TRUE, 'Desk drawer stuck'),
(36, 352.6, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, TRUE, 'Stained carpet near bed'),
(37, 138.74, 'TV, Air Condition, Fridge', 'Double', 'None', FALSE, TRUE, 'Lighting issues in bathroom'),
(37, 181.47, 'TV, Air Condition, Fridge', 'Quad', 'Sea', FALSE, FALSE, NULL),
(37, 261.03, 'TV, Air Condition, Fridge', 'Triple', 'Mountain', FALSE, FALSE, NULL),
(37, 317.51, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(37, 358.14, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, FALSE, NULL),
(38, 168.39, 'TV, Air Condition, Fridge', 'Double', 'Sea', FALSE, FALSE, NULL),
(38, 207.02, 'TV, Air Condition, Fridge', 'Quad', 'Mountain', TRUE, FALSE, NULL),
(38, 231.42, 'TV, Air Condition, Fridge', 'Double', 'Sea', TRUE, TRUE, 'Loose tiles in shower'),
(38, 280.07, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(38, 340.44, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, TRUE, 'Lighting issues in bathroom'),
(39, 166.36, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, TRUE, 'AC not working'),
(39, 207.33, 'TV, Air Condition, Fridge', 'Quad', 'Sea', TRUE, FALSE, NULL),
(39, 249.58, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(39, 285.53, 'TV, Air Condition, Fridge', 'Double', 'Mountain', TRUE, FALSE, NULL),
(39, 355.78, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(40, 150.46, 'TV, Air Condition, Fridge', 'Single', 'Mountain', TRUE, TRUE, 'Leaky faucet in bathroom'),
(40, 216.36, 'TV, Air Condition, Fridge', 'Triple', 'Sea', TRUE, FALSE, NULL),
(40, 266.2, 'TV, Air Condition, Fridge', 'Quad', 'None', TRUE, FALSE, NULL),
(40, 293.78, 'TV, Air Condition, Fridge', 'Single', 'Sea', FALSE, FALSE, NULL),
(40, 330.06, 'TV, Air Condition, Fridge', 'Triple', 'Sea', FALSE, FALSE, NULL);