SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Renting;
DROP TABLE IF EXISTS Booking;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Hotel;
DROP TABLE IF EXISTS HotelChain;

SET FOREIGN_KEY_CHECKS = 1;